context:
  name: cython-cmake
  version: "0.2.0"
  username: scikit-build

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com//${{ username }}/${{ name|lower }}/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 0673545871646e1736a2aaaf29f0f96ad1033da8fa6e457ee1cb99289048b8ac

build:
  script: ${{ PYTHON }} -m pip install --no-build-isolation --no-deps -vv .
  number: 0
  noarch: python

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >=${{ python_min }}
    - importlib_resources

tests:
  - script:
    - python -m pytest --durations=20
    files:
      source:
        - tests/
        - src/
        - pyproject.toml
    requirements:
      run:
        - ${{ compiler("c") }}
        - ${{ compiler("cxx") }}
        - ${{ stdlib("c") }}
        - python ${{ python_min }}.*
        - pytest
        - cython
        - scikit-build-core
        - ninja
        - cmake >=3.21
        - make


about:
  homepage: https://github.com/scikit-build/cython-cmake
  summary: CMake helpers for building Cython modules
  license: Apache-2.0
  license_file: LICENSE
  repository: https://github.com/scikit-build/cython-cmake

extra:
  recipe-maintainers:
    - conda-forge/scikit-build
